[package]
name = "fbx_direct"
version = "0.1.1"
authors = ["Takuma Yoshioka <nu11p0.6477@gmail.com>"]

license = "MIT"

[dependencies]
log = "^0.3.4"
byteorder = "^0.4.2"
flate2 = "^0.2.11"

[dev-dependencies]
env_logger = "^0.3.2"
